package io.paradaux.business.model;

import io.paradaux.hibernia.framework.models.HiberniaPlayer;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.time.LocalDateTime;
import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class FirmPlayer implements HiberniaPlayer {
    private String playerUuid;       // CHAR(36)
    private String currentName;      // VARCHAR(32) — widened for Floodgate Bedrock names (economy-flyway V12)
    private String nameLower;        // generated by DB (LOWER(current_name))
    private LocalDateTime firstSeen; // TIMESTAMP
    private LocalDateTime lastSeen;  // TIMESTAMP

    public UUID getUniqueId() {
        return UUID.fromString(playerUuid);
    }
}
